name: pretty-test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Ensures the correct branch is checked out for pull requests
          ref: ${{ github.head_ref }}

      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: npm install
      - run: npm run build

      - name: Check Prettier format
        run: npm run format
        continue-on-error: true

      - name: Fixing prettier format
        if: ${{ failure() }}
        run: |
          npm run format:fix
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: prettier-format code"
          git push
